import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import { NavigationBar } from "@/components/NavigationBar";
import { getUsers } from "@/prismaClient/queries/getUsers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const users = await getUsers();

  console.log("this is the users", users);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}

// theme source: https://ui.shadcn.com/docs/installation/next
// integrating next js prisma and postgres https://vercel.com/guides/nextjs-prisma-postgres
